In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import solve

In [2]:
df = pd.read_csv('football_matches_2024_2025.csv')

In [3]:
df.head

<bound method NDFrame.head of      competition_code       competition_name     season  match_id  matchday  \
0                  PL         Premier League  2024/2025    497410         1
1                  PL         Premier League  2024/2025    497411         1
2                  PL         Premier League  2024/2025    497412         1
3                  PL         Premier League  2024/2025    497413         1
4                  PL         Premier League  2024/2025    497414         1
...               ...                    ...        ...       ...       ...
1936               CL  UEFA Champions League  2024/2025    524046         8
1937               CL  UEFA Champions League  2024/2025    524053         8
1938               CL  UEFA Champions League  2024/2025    524064         8
1939               CL  UEFA Champions League  2024/2025    524068         8
1940               CL  UEFA Champions League  2024/2025    524072         8

               stage    status                   date_utc           referee  \
0     REGULAR_SEASON  FINISHED  2024-08-16 19:00:00+00:00      Robert Jones
1     REGULAR_SEASON  FINISHED  2024-08-17 11:30:00+00:00      Tim Robinson
2     REGULAR_SEASON  FINISHED  2024-08-17 14:00:00+00:00    Jarred Gillett
3     REGULAR_SEASON  FINISHED  2024-08-17 14:00:00+00:00      Simon Hooper
4     REGULAR_SEASON  FINISHED  2024-08-17 14:00:00+00:00      Craig Pawson
...              ...       ...                        ...               ...
1936    LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00    Clément Turpin
1937    LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00  Maurizio Mariani
1938    LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00       Espen Eskås
1939    LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00    Mikola Balakin
1940    LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00      Davide Massa

      home_team_id  ... fulltime_home  fulltime_away halftime_home  \
0               66  ...             1              0             0
1              349  ...             0              2             0
2               57  ...             2              0             1
3               62  ...             0              3             0
4               67  ...             1              0             1
...            ...  ...           ...            ...           ...
1936            58  ...             4              2             2
1937           298  ...             1              2             1
1938           512  ...             0              3             0
1939          2021  ...             1              0             1
1940            10  ...             1              4             0

      halftime_away  goal_difference  total_goals  match_outcome  home_points  \
0                 0                1            1       Home Win            3
1                 0               -2            2       Away Win            0
2                 0                2            2       Home Win            3
3                 1               -3            3       Away Win            0
4                 0                1            1       Home Win            3
...             ...              ...          ...            ...          ...
1936              2                2            6       Home Win            3
1937              2               -1            3       Away Win            0
1938              1               -3            3       Away Win            0
1939              0                1            1       Home Win            3
1940              3               -3            5       Away Win            0

      away_points referee_id
0               0          1
1               3          2
2               0          3
3               3          4
4               0          5
...           ...        ...
1936            0        114
1937            3         58
1938            3        133
1939            0        157
1940            3         66

[1941 rows x 23 columns]>

In [4]:
ucl_all = df[
    (df["competition_name"] == "UEFA Champions League") &
    (df["season"] == "2024/2025")
]

print(ucl_all)

     competition_code       competition_name     season  match_id  matchday  \
1752               CL  UEFA Champions League  2024/2025    524120         0
1753               CL  UEFA Champions League  2024/2025    523998         1
1754               CL  UEFA Champions League  2024/2025    524039         1
1755               CL  UEFA Champions League  2024/2025    523934         1
1756               CL  UEFA Champions League  2024/2025    523967         1
...               ...                    ...        ...       ...       ...
1936               CL  UEFA Champions League  2024/2025    524046         8
1937               CL  UEFA Champions League  2024/2025    524053         8
1938               CL  UEFA Champions League  2024/2025    524064         8
1939               CL  UEFA Champions League  2024/2025    524068         8
1940               CL  UEFA Champions League  2024/2025    524072         8

             stage    status                   date_utc  \
1752         FINAL  FINISHED  2025-05-31 19:00:00+00:00
1753  LEAGUE_STAGE  FINISHED  2024-09-17 16:45:00+00:00
1754  LEAGUE_STAGE  FINISHED  2024-09-17 16:45:00+00:00
1755  LEAGUE_STAGE  FINISHED  2024-09-17 19:00:00+00:00
1756  LEAGUE_STAGE  FINISHED  2024-09-17 19:00:00+00:00
...            ...       ...                        ...
1936  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1937  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1938  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1939  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1940  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00

                            referee  home_team_id  ... fulltime_home  \
1752                  István Kovács           524  ...             5
1753  Alejandro Hernández Hernández           109  ...             3
1754                 Georgi Kabakov          1871  ...             0
1755          Juan Martínez Munuera             5  ...             9
1756                    Halil Meler            86  ...             3
...                             ...           ...  ...           ...
1936                 Clément Turpin            58  ...             4
1937               Maurizio Mariani           298  ...             1
1938                    Espen Eskås           512  ...             0
1939                 Mikola Balakin          2021  ...             1
1940                   Davide Massa            10  ...             1

      fulltime_away halftime_home  halftime_away  goal_difference  \
1752              0             2              0                5
1753              1             2              0                2
1754              3             0              2               -3
1755              2             3              0                7
1756              1             0              0                2
...             ...           ...            ...              ...
1936              2             2              2                2
1937              2             1              2               -1
1938              3             0              1               -3
1939              0             1              0                1
1940              4             0              3               -3

      total_goals  match_outcome  home_points  away_points referee_id
1752            5       Home Win            3            0        130
1753            4       Home Win            3            0         31
1754            3       Away Win            0            3        131
1755           11       Home Win            3            0         44
1756            4       Home Win            3            0        132
...           ...            ...          ...          ...        ...
1936            6       Home Win            3            0        114
1937            3       Away Win            0            3         58
1938            3       Away Win            0            3        133
1939            1       Home Win            3            0        157
1940            5       Away Win            0            3         66

[189 rows x 23 columns]

In [5]:
ucl_league= df[
    (df["competition_name"] == "UEFA Champions League") &
    (df["season"] == "2024/2025") &
    (df["stage"] == "LEAGUE_STAGE")
]


print(ucl_league)

     competition_code       competition_name     season  match_id  matchday  \
1753               CL  UEFA Champions League  2024/2025    523998         1
1754               CL  UEFA Champions League  2024/2025    524039         1
1755               CL  UEFA Champions League  2024/2025    523934         1
1756               CL  UEFA Champions League  2024/2025    523967         1
1757               CL  UEFA Champions League  2024/2025    523968         1
...               ...                    ...        ...       ...       ...
1936               CL  UEFA Champions League  2024/2025    524046         8
1937               CL  UEFA Champions League  2024/2025    524053         8
1938               CL  UEFA Champions League  2024/2025    524064         8
1939               CL  UEFA Champions League  2024/2025    524068         8
1940               CL  UEFA Champions League  2024/2025    524072         8

             stage    status                   date_utc  \
1753  LEAGUE_STAGE  FINISHED  2024-09-17 16:45:00+00:00
1754  LEAGUE_STAGE  FINISHED  2024-09-17 16:45:00+00:00
1755  LEAGUE_STAGE  FINISHED  2024-09-17 19:00:00+00:00
1756  LEAGUE_STAGE  FINISHED  2024-09-17 19:00:00+00:00
1757  LEAGUE_STAGE  FINISHED  2024-09-17 19:00:00+00:00
...            ...       ...                        ...
1936  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1937  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1938  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1939  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00
1940  LEAGUE_STAGE  FINISHED  2025-01-29 20:00:00+00:00

                            referee  home_team_id  ... fulltime_home  \
1753  Alejandro Hernández Hernández           109  ...             3
1754                 Georgi Kabakov          1871  ...             0
1755          Juan Martínez Munuera             5  ...             9
1756                    Halil Meler            86  ...             3
1757                    Espen Eskås            98  ...             1
...                             ...           ...  ...           ...
1936                 Clément Turpin            58  ...             4
1937               Maurizio Mariani           298  ...             1
1938                    Espen Eskås           512  ...             0
1939                 Mikola Balakin          2021  ...             1
1940                   Davide Massa            10  ...             1

      fulltime_away halftime_home  halftime_away  goal_difference  \
1753              1             2              0                2
1754              3             0              2               -3
1755              2             3              0                7
1756              1             0              0                2
1757              3             1              2               -2
...             ...           ...            ...              ...
1936              2             2              2                2
1937              2             1              2               -1
1938              3             0              1               -3
1939              0             1              0                1
1940              4             0              3               -3

      total_goals  match_outcome  home_points  away_points referee_id
1753            4       Home Win            3            0         31
1754            3       Away Win            0            3        131
1755           11       Home Win            3            0         44
1756            4       Home Win            3            0        132
1757            4       Away Win            0            3        133
...           ...            ...          ...          ...        ...
1936            6       Home Win            3            0        114
1937            3       Away Win            0            3         58
1938            3       Away Win            0            3        133
1939            1       Home Win            3            0        157
1940            5       Away Win            0            3         66

[144 rows x 23 columns]

In [6]:
# Home team perspective
home = ucl_league[[
    "match_id",
    "home_team",
    "away_team",
    "fulltime_home",
    "fulltime_away"
]].copy()

home["team"] = home["home_team"]
home["opponent"] = home["away_team"]

home["result"] = home.apply(
    lambda x: "Win" if x["fulltime_home"] > x["fulltime_away"]
    else "Draw" if x["fulltime_home"] == x["fulltime_away"]
    else "Loss",
    axis=1
)

home = home[["match_id", "team", "opponent", "result"]]

In [7]:
# Away team perspective
away = ucl_league[[
    "match_id",
    "home_team",
    "away_team",
    "fulltime_home",
    "fulltime_away"
]].copy()

away["team"] = away["away_team"]
away["opponent"] = away["home_team"]

away["result"] = away.apply(
    lambda x: "Win" if x["fulltime_away"] > x["fulltime_home"]
    else "Draw" if x["fulltime_away"] == x["fulltime_home"]
    else "Loss",
    axis=1
)

away = away[["match_id", "team", "opponent", "result"]]

In [8]:
team_match_results = pd.concat([home, away], ignore_index=True)

In [9]:
team_name1 = "Arsenal FC"
team_name2 = "AC Milan"

arsenal_matches = team_match_results[
    team_match_results["team"] == team_name1
]

print(arsenal_matches)

acMilan_matches = team_match_results[
    team_match_results["team"] == team_name2
]

print(acMilan_matches)

     match_id        team                    opponent result
24     523992  Arsenal FC      Paris Saint-Germain FC    Win
40     523993  Arsenal FC         FK Shakhtar Donetsk    Win
104    523995  Arsenal FC                AS Monaco FC    Win
122    523994  Arsenal FC           GNK Dinamo Zagreb    Win
158    523973  Arsenal FC                 Atalanta BC   Draw
209    523949  Arsenal FC    FC Internazionale Milano   Loss
223    524033  Arsenal FC  Sporting Clube de Portugal    Win
284    524053  Arsenal FC                   Girona FC    Win
     match_id      team              opponent result
4      523968  AC Milan          Liverpool FC   Loss
36     523969  AC Milan        Club Brugge KV    Win
102    523970  AC Milan      FK Crvena Zvezda    Win
121    523971  AC Milan             Girona FC    Win
167    523981  AC Milan   Bayer 04 Leverkusen   Loss
202    523965  AC Milan        Real Madrid CF    Win
216    524057  AC Milan  ŠK Slovan Bratislava    Win
277    524009  AC Milan     GNK Dinamo Zagreb   Loss

In [10]:
formatted_output = arsenal_matches.apply(
    lambda x: f"{x['team']} | {x['opponent']} | {x['result']}",
    axis=1
)

print(formatted_output.to_string(index=False))

    Arsenal FC | Paris Saint-Germain FC | Win
       Arsenal FC | FK Shakhtar Donetsk | Win
              Arsenal FC | AS Monaco FC | Win
         Arsenal FC | GNK Dinamo Zagreb | Win
              Arsenal FC | Atalanta BC | Draw
 Arsenal FC | FC Internazionale Milano | Loss
Arsenal FC | Sporting Clube de Portugal | Win
                 Arsenal FC | Girona FC | Win

In [11]:
formatted_output = acMilan_matches.apply(
    lambda x: f"{x['team']} | {x['opponent']} | {x['result']}",
    axis=1
)

print(formatted_output.to_string(index=False))

       AC Milan | Liverpool FC | Loss
      AC Milan | Club Brugge KV | Win
    AC Milan | FK Crvena Zvezda | Win
           AC Milan | Girona FC | Win
AC Milan | Bayer 04 Leverkusen | Loss
      AC Milan | Real Madrid CF | Win
AC Milan | ŠK Slovan Bratislava | Win
  AC Milan | GNK Dinamo Zagreb | Loss

In [12]:
#COLLEY RANK

In [34]:
df = team_match_results.copy()

df["team"] = df["team"].astype(str).str.strip()
df["opponent"] = df["opponent"].astype(str).str.strip()
df["result"] = df["result"].astype(str).str.strip().str.lower()

In [36]:
matches = (
    df.sort_values(["match_id", "team"])
      .groupby("match_id")
      .agg({"team": list, "result": list})
      .reset_index()
)

matches["team_i"] = matches["team"].apply(lambda x: x[0])
matches["team_j"] = matches["team"].apply(lambda x: x[1])
matches["result_i"] = matches["result"].apply(lambda x: x[0])
matches["result_j"] = matches["result"].apply(lambda x: x[1])

matches = matches[["match_id", "team_i", "team_j", "result_i", "result_j"]]

print("matches:", len(matches))
print(matches.head())

matches: 144
   match_id             team_i                  team_j result_i result_j
0    523932  FC Bayern München  Paris Saint-Germain FC      win     loss
1    523933  FC Bayern München  Sport Lisboa e Benfica      win     loss
2    523934  FC Bayern München       GNK Dinamo Zagreb      win     loss
3    523935  FC Bayern München    ŠK Slovan Bratislava      win     loss
4    523936  Borussia Dortmund            FC Barcelona     loss      win

In [37]:
bad = matches[
    ~(
        ((matches["result_i"] == "win") & (matches["result_j"] == "loss")) |
        ((matches["result_i"] == "loss") & (matches["result_j"] == "win")) |
        ((matches["result_i"] == "draw") & (matches["result_j"] == "draw"))
    )
]

print("bad matches:", len(bad))
bad.head()

bad matches: 0

Empty DataFrame
Columns: [match_id, team_i, team_j, result_i, result_j]
Index: []

In [38]:
teams = sorted(set(matches["team_i"]).union(set(matches["team_j"])))
team_to_id = {t:i for i,t in enumerate(teams)}
n = len(teams)

wins = np.zeros(n)
losses = np.zeros(n)
N = np.zeros((n,n))

In [39]:
for _, row in matches.iterrows():
    i = team_to_id[row["team_i"]]
    j = team_to_id[row["team_j"]]

    N[i,j] = 1
    N[j,i] = 1

    if row["result_i"] == "win":
        wins[i] += 1
        losses[j] += 1
    elif row["result_i"] == "loss":
        wins[j] += 1
        losses[i] += 1

In [41]:
games = N.sum(axis=1)
print(np.unique(games))

print(pd.Series(wins + losses).value_counts())

[8.]
7.0    14
8.0    13
6.0     5
5.0     4
Name: count, dtype: int64

In [42]:
C = np.zeros((n,n))
b = np.zeros(n)

for i in range(n):
    C[i,i] = 2 + games[i]   # <-- 10 for everyone
    b[i] = 1 + (wins[i] - losses[i]) / 2

for i in range(n):
    for j in range(n):
        if i != j:
            C[i,j] = -N[i,j]

ratings = np.linalg.solve(C, b)

In [49]:
colley = pd.DataFrame({
    "team": teams,
    "rating": ratings,
    "wins": wins,
    "losses": losses,
    "games": games
}).sort_values("rating", ascending=False).reset_index(drop=True)

colley.insert(0, "rank", colley.index + 1)

colley.head(36)

    rank                        team    rating  wins  losses  games
0      1                Liverpool FC  0.806670   7.0     1.0    8.0
1      2                  Arsenal FC  0.755880   6.0     1.0    8.0
2      3                FC Barcelona  0.751644   6.0     1.0    8.0
3      4    FC Internazionale Milano  0.698783   6.0     1.0    8.0
4      5                   Lille OSC  0.687886   5.0     2.0    8.0
5      6         Bayer 04 Leverkusen  0.675881   5.0     2.0    8.0
6      7              Real Madrid CF  0.642226   5.0     3.0    8.0
7      8     Club Atlético de Madrid  0.632300   6.0     2.0    8.0
8      9                 Atalanta BC  0.628580   4.0     1.0    8.0
9     10                AS Monaco FC  0.615814   4.0     3.0    8.0
10    11              Aston Villa FC  0.606395   5.0     2.0    8.0
11    12           Borussia Dortmund  0.596831   5.0     3.0    8.0
12    13           FC Bayern München  0.595874   5.0     3.0    8.0
13    14      Sport Lisboa e Benfica  0.593412   4.0     3.0    8.0
14    15                         PSV  0.584837   4.0     2.0    8.0
15    16                    AC Milan  0.575389   5.0     3.0    8.0
16    17                 Juventus FC  0.556919   3.0     2.0    8.0
17    18      Paris Saint-Germain FC  0.534624   4.0     3.0    8.0
18    19           Stade Brestois 29  0.531302   4.0     3.0    8.0
19    20         Feyenoord Rotterdam  0.522651   4.0     3.0    8.0
20    21              Club Brugge KV  0.507148   3.0     3.0    8.0
21    22  Sporting Clube de Portugal  0.497926   3.0     3.0    8.0
22    23           GNK Dinamo Zagreb  0.493116   3.0     3.0    8.0
23    24                   Celtic FC  0.479521   3.0     2.0    8.0
24    25          Manchester City FC  0.466274   3.0     3.0    8.0
25    26             Bologna FC 1909  0.427942   1.0     4.0    8.0
26    27         FK Shakhtar Donetsk  0.374490   2.0     5.0    8.0
27    28               VfB Stuttgart  0.366167   3.0     4.0    8.0
28    29            FK Crvena Zvezda  0.330970   2.0     6.0    8.0
29    30               SK Sturm Graz  0.292221   2.0     6.0    8.0
30    31             AC Sparta Praha  0.262280   1.0     6.0    8.0
31    32                  RB Leipzig  0.257074   1.0     7.0    8.0
32    33        FC Red Bull Salzburg  0.229438   1.0     7.0    8.0
33    34                   Girona FC  0.215468   1.0     7.0    8.0
34    35              BSC Young Boys  0.123655   0.0     8.0    8.0
35    36        ŠK Slovan Bratislava  0.082411   0.0     8.0    8.0

In [44]:
print("mean:", ratings.mean())
print("min:", ratings.min())
print("max:", ratings.max())

mean: 0.5
min: 0.08241096440616241
max: 0.8066703907921624